id: CreatureHiro
full_name: 二阶堂希罗（魔女化）
emotion_count: 25
font: font3
text:
  - text: 二
    font_color: [239, 79, 84]
    font_size: 136
  - text: 阶堂
    font_size: 76
  - text: 希
    font_size: 116
  - text: 罗
    font_size: 76
offset: [-160, 1790]
offsetX:
  "2": -40
  "3": -40
  "5": -40
  "6": -330
  "7": -330
  "8": -330
  "9": -330
  "12": -40
  "15": -40
scale: 0.41
emo:
  平静: [1, 2, 3, 5, 8, 9, 10, 11]
  喜悦: [3, 5, 8, 10, 11, 25]
  喜爱: [25]
  惊讶: [1, 15, 23, 24]
  困惑: [1, 15, 17, 23]
  无语: [1, 2, 4, 15, 16, 23, 24, 25]
  悲伤: [9]
  愤怒: [4, 7, 14, 17, 20, 22, 23, 24]
  恐惧: [12, 13, 15]
