id: yuki
full_name: 月代雪
emotion_count: 20
offset: [-550, 1850]
scale: 0.47
font: font3
text:
  - text: 月
    font_color: [195, 209, 231]
    font_size: 136
  - text: 代
    font_size: 76
  - text: 雪
    font_size: 116
offsetY:
  "12": 50
emo:
  平静: [2, 3, 4, 5]
  喜悦: [2, 3, 4, 5, 6, 7, 8, 18, 19]
  喜爱: [8, 18, 19]
  惊讶: [9, 13, 15, 16, 17]
  困惑: [9, 13, 15, 20]
  无语: [1, 4, 5, 10, 11, 14, 16, 17, 19, 20]
  悲伤: [17]
  愤怒: [1, 7, 13, 16, 17]
  恐惧: [16, 17]
